content/introduction:
  - manifests/modules/introduction/**/*
  - website/docs/introduction/**/*

content/fundamentals:
  - manifests/modules/fundamentals/**/*
  - website/docs/fundamentals/**/*

content/autoscaling:
  - manifests/modules/autoscaling/**/*
  - website/docs/autoscaling/**/*

content/security:
  - manifests/modules/security/**/*
  - website/docs/security/**/*

content/networking:
  - manifests/modules/networking/**/*
  - website/docs/networking/**/*

content/observability:
  - manifests/modules/observability/**/*
  - website/docs/observability/**/*

content/cost-optimization:
  - manifests/modules/costoptimization/**/*
  - website/docs/costoptimization/**/*

content/fastpaths:
  - manifests/modules/fastpaths/**/*
  - website/docs/fastpaths/**/*
