server:
  replicas: 1
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
      service.beta.kubernetes.io/load-balancer-source-ranges: $INBOUND_CIDRS

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

redis-ha:
  enabled: false

configs:
  cm:
    timeout.reconciliation: 5s
