apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-files-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-files-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: s3files:${S3_FILES_ID}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-files-claim
  namespace: ui
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-files-sc
  resources:
    requests:
      storage: 5Gi
  volumeName: s3-files-pv
