apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  namespace: catalog
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "Y2F0YWxvZw=="
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "ZFltTmZXVjR1RXZUem9GdQ=="
