{
 "title": "Retail Business Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Watch Orders by Product ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(watch_orders_total{productId=\"a0a4f044-b040-410d-8ead-4de0446aec7e\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(watch_orders_total{productId=\"808a2de1-1aaa-4c25-a9b9-6612e8f29a38\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(watch_orders_total{productId=\"510a0d7e-8e83-4193-b483-e27e09ddc34d\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(watch_orders_total{productId=\"6d62d909-f957-430e-8689-b5129c0bb75e\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum(watch_orders_total{productId=\"*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 17 },
   "targets": [
    { "expr": "sum(watch_orderTotal)", "legendFormat": "__auto" }
   ]
  }
 ]
}