{
 "title": "Order Service Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Orders by Product ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(productId) (watch_orders_total{productId!=\"*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(watch_orders_total{productId=\"*\"}) by (productId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (productId)(rate(watch_orders_total{productId=\"*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}